### ISSUE TITLE
Using wrong key to get cached when running i Hybrid mode

### ISSUE THREAD

**Issue by ThomasSkyldahl** [catcherwong/Ocelot.Cache.EasyCaching#1]
Hi I found a bug in the code:
https://github.com/catcherwong/Ocelot.Cache.EasyCaching/blob/c7d0a9c141d489ee22c713901b5b3cfb23941dfb/src/Ocelot.Cache.EasyCaching/OcelotEasyCachingCache.cs#L81

As seen the get call doesn't use the cacheKey but the region so it will never get a value back as the set uses the "region:key" format

**Comment by catcherwong** [comment]
@ThomasSkyldahl  Thanks for your interest in this project.

Could you submit a PR to fix this bug?

**Comment by ThomasSkyldahl** [comment]
@catcherwong sorry for the late reply, I will try fixing it and send a pull request

**Comment by catcherwong** [comment]
Release a new version for this issue.
